name: Auto Version & Publish NuGet

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "src/**" ]

jobs:
  increment-version:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUBACCESSTOKEN }}

    - name: Import GPG & Enable Git Signing
      # You may pin to the exact commit or the version.
      # uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.COMMIT_SIGNINGKEY }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true
        git_push_gpgsign: true
  
    - name: Reset Origin
      run: |
        git remote set-url origin "https://cbcrouse:${{ secrets.GITHUBACCESSTOKEN }}@github.com/cbcrouse/Versioning.NET.git"
        git checkout ${{ github.ref_name }}

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.x'

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.x'

    - name: Install Versioning.NET
      run: |
        dotnet tool install --global Versioning.NET

    - name: Increment Version
      run: |
        dotnet-version increment-version-with-git-hints -g "." --branch-name ${{ github.ref_name }} --author-email ${{ vars.COMMIT_SIGNING_EMAIL }}

  publish-nuget:
    needs: increment-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore NuGet packages
        run: dotnet restore src/Versioning.NET/Versioning.NET.csproj

      - name: Pack project
        run: dotnet pack src/Versioning.NET/Versioning.NET.csproj --configuration Release --no-restore /m

      - name: Publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
        run: dotnet nuget push "src/Versioning.NET/nupkg/*.nupkg" --skip-duplicate --api-key $NUGET_API_KEY --source $NUGET_SOURCE